drop table "NYPD_Crime";

create table "NYPD_Crime" (
"CMPLNT_NUM" VARCHAR (50) NULL,
"ADDR_PCT_CD" INT NULL,
"BORO_NM" VARCHAR (50) NULL,
"CMPLNT_FR_DT" DATE NULL,
"CMPLNT_FR_TM" TIME with time zone NULL,
"CMPLNT_TO_DT" DATE NULL,
"CMPLNT_TO_TM" TIME with time zone NULL,
"LAW_CAT_CD" VARCHAR (100) NULL,
"OFNS_DESC" VARCHAR (100) NULL,
"PARKS_NM" VARCHAR (100) NULL,
"PATROL_BORO" VARCHAR (100) NULL,
"PD_DESC" VARCHAR (100) NULL,
"PREM_TYP_DESC" VARCHAR (100) NULL,
"RPT_DT" DATE NULL,
"SUSP_AGE_GROUP" VARCHAR (50) NULL,
"SUSP_RACE" VARCHAR (50) NULL,
"SUSP_SEX" VARCHAR (10) NULL,
"VIC_AGE_GROUP" VARCHAR (50) NULL,
"VIC_RACE" VARCHAR (50) NULL,
"VIC_SEX" VARCHAR (10) NULL,
"X_COORD_CD" INT NULL,
"Y_COORD_CD" INT NULL,
"Latitude" DECIMAL NULL,
"Longitude" DECIMAL NULL)

select * from "NYPD_Crime"